server:
  port: 8081
  
security:
  oauth2:
    client:
      clientId: 3ijui517bfu90b9tit52tdgtr2
      clientSecret: dsh9ir8j111t9mukdq9lu929ffkae335e2hrmj8svhrrqb2uv8a
      accessTokenUri: https://BlaQ.auth.eu-west-1.amazoncognito.com/oauth2/token
      userAuthorizationUri:  https://BlaQ.auth.eu-west-1.amazoncognito.com/oauth2/authorize
      tokenName: Authorization
      authenticationScheme: header
      clientAuthenticationScheme: header
      auto-approve-scopes: true
      authorized-grant-types:
        authorization_code
    resource:
      userInfoUri: https://BlaQ.auth.eu-west-1.amazoncognito.com/oauth2/userInfo
      #preferTokenInfo: false